name: Release

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: mlugg/setup-zig@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl,aarch64-unknown-linux-musl,x86_64-apple-darwin,aarch64-apple-darwin
      - uses: taiki-e/install-action@cargo-zigbuild
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cargo zigbuild --no-default-features -r --target x86_64-unknown-linux-musl
          cargo zigbuild --no-default-features -r --target aarch64-unknown-linux-musl
          cargo zigbuild --no-default-features -r --target universal2-apple-darwin
          mv target/aarch64-unknown-linux-musl/release/legalize-kr-compiler legalize-kr-compiler-aarch64-unknown-linux-musl
          mv target/x86_64-unknown-linux-musl/release/legalize-kr-compiler legalize-kr-compiler-x86_64-unknown-linux-musl
          mv target/universal2-apple-darwin/release/legalize-kr-compiler legalize-kr-compiler-universal2-apple-darwin
          tar -cvf binaries.tar \
            legalize-kr-compiler-aarch64-unknown-linux-musl \
            legalize-kr-compiler-x86_64-unknown-linux-musl \
            legalize-kr-compiler-universal2-apple-darwin

          VERSION="v$(grep '^version' Cargo.toml | head -1 | sed 's/.*"\(.*\)"/\1/')"
          TAG="${VERSION}-$(date -u +%Y%m%d%H%M%S)"
          git tag "$TAG"
          git push origin "$TAG"
          gh release create "$TAG" --title "$TAG" --generate-notes \
            legalize-kr-compiler-aarch64-unknown-linux-musl \
            legalize-kr-compiler-x86_64-unknown-linux-musl \
            legalize-kr-compiler-universal2-apple-darwin
